# Site settings
name: "Yarfik blog"
description: ""
url: "http://yarfik.github.io"
paginate: 10
markdown: kramdown

# Build settings
permalink: pretty
sass:
  sass_dir: css

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

comments:
  facebook:
    appid: "343977016299572"
    num_posts: 10
    colorscheme: "light"
    order_by: "reverse_time"